export const products = [{
  id: '1',
  name: 'Frontend',
  price: '60.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '2',
  name: 'Java',
  price: '120.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '3',
  name: 'JS',
  price: '90.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '4',
  name: 'TYPO3 Extension - Mapbox',
  price: '190.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sitenenatis a',
  averageRating: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '5',
  name: 'Webseite umziehen',
  price: '75.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '6',
  name: 'Webseite umziehen',
  price: '200.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '7',
  name: 'Webseite umziehen',
  price: '100.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '8',
  name: 'Webseite umziehen',
  price: '40.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
}, {
  id: '9',
  name: 'Webseite umziehen',
  price: '54.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
},
{
  id: '10',
  name: 'Webseite umziehen',
  price: '330.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
},
{
  id: '11',
  name: 'Webseite umziehen',
  price: '230.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}, {
  id: '12',
  name: 'Webseite umziehen',
  price: '180.00',
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel enim quam. Mauris nisl tellus, fringilla sed cursus eu, convallis non diam. Mauris quis fringilla nunc. Aenean leo lacus, lobortis sit amet v.',
  time: '5.0',
  comment: 'Lorem Ipsum',
}];
